In [1]:
import pandas as pd
import numpy as np

   order_id  supplier_id  product_id  quantity  order_date delivery_date
0   0          1          1.0           2      50....
1   1          2          2.0           5      30....
2   2          3          3.0           1     100....
3   3          4          4.0           6      20....
4   4          5          5.0           3      75....
5   5          6          1.0           7      15....
6   6          7          2.0           4     200....
7   7          8          NaN           5      40....
8   8          9          3.0           2      60....
9   9         10          4.0           1      90....
10  10        11          5.0           6      25....
11  11        12          1.0           3       Na...
12  12        13          2.0           7      55....
13  13        14          3.0           4      35....
14  14        15          NaN           1      80....

In [8]:
df = pd.read_csv('/content/orders_01.csv')
display(df)

    order_id  supplier_id  product_id  quantity  order_date delivery_date
0          1          1.0           2      50.0  2025-06-01    2025-06-06
1          2          2.0           5      30.0  2025-06-05    06/08/2025
2          3          3.0           1     100.0  2025-06-07    2025-06-17
3          4          4.0           6      20.0  2025-06-10           NaN
4          5          5.0           3      75.0  06/11/2025    2025-06-15
5          6          1.0           7      15.0  2025-06-12    2025-06-17
6          7          2.0           4     200.0  2025-06-13    2025-06-16
7          8          NaN           5      40.0  2025-06-14    2025-06-19
8          9          3.0           2      60.0  2025-06-15    2025/06/20
9         10          4.0           1      90.0  2025-06-16           NaN
10        11          5.0           6      25.0  2025-06-17    2025-06-22
11        12          1.0           3       NaN  2025-06-18    2025-06-23
12        13          2.0           7      55.0  2025-06-19    2025-06-21
13        14          3.0           4      35.0  2025-06-20    2025-06-25
14        15          NaN           1      80.0  2025-06-21    2025-06-26

In [9]:
df = df.dropna(subset=['supplier_id'])
median_qty = df['quantity'].median()
df['quantity'] = df['quantity'].fillna(median_qty)
df['order_date'] = pd.to_datetime(df['order_date'], format='mixed')
df['delivery_date'] = pd.to_datetime(df['delivery_date'], format='mixed')
df['supplier_id'] = df['supplier_id'].astype(int)
df['quantity'] = df['quantity'].astype(int)

In [10]:
today = pd.Timestamp.today().normalize()

In [11]:
df['delay_days'] = np.where(
    df['delivery_date'].notna(),
    (today - df['delivery_date']).dt.days,
    (today - df['order_date']).dt.days
)

In [12]:
df['is_delayed'] = np.where(df['delay_days'] > 0, 1, 0)

In [13]:
print("--- Final Processed Data ---")
print(df[['order_id', 'supplier_id', 'product_id', 'quantity',
          'order_date', 'delivery_date', 'delay_days', 'is_delayed']])

print("\n--- Delay Summary ---")
print(f"Total orders: {len(df)}")
print(f"Delayed orders: {df['is_delayed'].sum()}")
print(f"On-time orders: {len(df) - df['is_delayed'].sum()}")

print("\n--- Delayed Orders Only ---")
print(df[df['is_delayed'] == 1][['order_id', 'supplier_id', 'delay_days']])

--- Final Processed Data ---
    order_id  supplier_id  product_id  quantity order_date delivery_date  \
0          1            1           2        50 2025-06-01    2025-06-06
1          2            2           5        30 2025-06-05    2025-06-08
2          3            3           1       100 2025-06-07    2025-06-17
3          4            4           6        20 2025-06-10           NaT
4          5            5           3        75 2025-06-11    2025-06-15
5          6            1           7        15 2025-06-12    2025-06-17
6          7            2           4       200 2025-06-13    2025-06-16
8          9            3           2        60 2025-06-15    2025-06-20
9         10            4           1        90 2025-06-16           NaT
10        11            5           6        25 2025-06-17    2025-06-22
11        12            1           3        52 2025-06-18    2025-06-23
12        13            2           7        55 2025-06-19    2025-06-21
13        14            3           4        35 2025-06-20    2025-06-25

    delay_days  is_delayed
0        381.0           1
1        379.0           1
2        370.0           1
3        377.0           1
4        372.0           1
5        370.0           1
6        371.0           1
8        367.0           1
9        371.0           1
10       365.0           1
11       364.0           1
12       366.0           1
13       362.0           1

--- Delay Summary ---
Total orders: 13
Delayed orders: 13
On-time orders: 0

--- Delayed Orders Only ---
    order_id  supplier_id  delay_days
0          1            1       381.0
1          2            2       379.0
2          3            3       370.0
3          4            4       377.0
4          5            5       372.0
5          6            1       370.0
6          7            2       371.0
8          9            3       367.0
9         10            4       371.0
10        11            5       365.0
11        12            1       364.0
12        13            2       366.0
13        14            3       362.0